---
project:
  description: Amazon::API
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm-module: Amazon::API
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - ChangeLog
  - NOTICE
  - NOTICE.botocore
  - LICENSE.botocore
  -
    share:
      - Amazon-API.pem
      - LICENSE.botocore
      - NOTICE
      - NOTICE.botocore
      - README.md
      - botocore-metadata.api
      - botocore-version.json
      - botocore.mk
      - buildspec-api.yml.in
      - module-names.json
      - release-notes.md
      - requires.cpan-dist
      - services.api
      - share/stub.pm.tmpl
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: https://github.com/rlauer6/Amazon-API/issues
  homepage: https://github.com/rlauer6/Amazon-API
  repository:
    type: git
    url: git@github.com:rlauer6/Amazon-API.git
    web: https://github.com/rlauer6/Amazon-API
